config/routes.rb
Rails.application.routes.draw do
  root 'calendars#index'
  resources :calendars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :plan, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  # １週間のカレンダーと予定が表示されるページ
  def index
    get_week
    @plan = Plan.new
  end

  # 予定の保存
  def create
    Plan.create(plan_params)
    redirect_to action: :index
  end

  private

  def plan_params
    params.require(:plan).permit(:date, :plan)
  end

  def get_week
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    # Dateオブジェクトは、日付を保持しています。下記のように`.today.day`とすると、今日の日付を取得できます。
    @todays_date = Date.today
    # 例)　今日が2月1日の場合・・・ Date.today.day => 1日

    @week_days = []

    plans = Plan.where(date: @todays_date..@todays_date + 6)
# テーブルplanの中の今日から＋6日間のデータを抜き取る。plansに代入。
    7.times do |x|
      today_plans = []
      plans.each do |plan|
        today_plans.push(plan.plan) if plan.date == @todays_date + x
      end
      # 7回繰り返す。pushは[]に押し込む。 plan plan はplanの中のplan（出産）をtoday_planに入れる。
      # plan.dataは出産の日日付。と = だった場合、[]にpushで入れ込む。today_planに。

     wday_num = Date.today.wday + x
    #  0が表示されるようにする。
     if wday_num >= 7
      wday_num = wday_num -7
     end
      days = { month: (@todays_date + x).month, date: (@todays_date+x).day, plans: today_plans, wday: wdays[wday_num ] }
      # wday はindex.htmlの<%= day[:wday]  %>のwday と同じにする必要がする。wday_numは40行目。今日の日付。（Date.today.wdayを代入）

      @week_days.push(days)
# これも繰り返し処理。7回。= { :month => (@todays_date + x).month, :date => (@todays_date+x).day, :plans => today_plans, :wday=> }　={はハッシュ　.manthは ～の9月。
  # daysの7個の情報をpush → @week_daysに、28行目の[]に押し込んでいる。
    end
  end
end


# [{month=>9,date,17,plans=>[]},{month=>9,date,18,plans=>[]}{month=>9,date,19,plans=>[]}{month=>9,date,20,plans=>[出産]}{month=>9,date,21,plans=>[]}{month=>9,date,22,plans=>[]}{month=>9,date,23,plans=>[]}]

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/index.html.erb
  <%= form_with model: @plan, url: calendars_path, class: 'form' do |f| %>
    <%= f.label :日付を選択, class: 'lavel' %>
    <%= f.date_field :date, class: 'date-select' %>
    <%= f.label :予定を入力, class: 'lavel' %>
    <%= f.text_field :plan, class: 'text-input' %>
    <%= f.submit '保存' %>
  <% end %>



  <div class='calendar'>
    <% @week_days.each do |day| %>
    <%# 7個繰り返し処理する。dayは全部の情報。月、日、予定。 %>
      <div class='item'>
        <div class='date'>
          <%= day[:month] %>/<%= day[:date] %>/<%= day[:wday]  %>
          <%# ハッシュの為。manth のみ。 %>
        </div>
        <ul class='content'>
        <% if day[:plans].length != 0 %>
        <%# 追加の予定があった場合。 %>
          <% day[:plans].each do |plan| %>
            <li class='plan-list'>・<%= plan %></li>
          <% end %>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingCurriculumRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>